name: namer_app
description: A new Flutter project.
version: 0.0.1+1
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^6.1.0   # Use a version that supports null safety
  latlong2: ^0.9.1      # Update to version compatible with null safety
  url_launcher: ^6.1.6
  english_words: ^4.0.0
  provider: ^6.0.0
  sqflite: ^2.3.3
  path: ^1.9.0
  async: ^2.11.0
  path_provider: ^2.0.2
  geocoding: ^2.0.0
  sqflite_common_ffi: ^2.3.3
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - ./assets/images/Logo.png
